
### 파이프라인 실행 (topic o)

GET http://localhost:8080/pipeline/topic/start?count=1000000
Accept: application/json



### 파이프라인 실행 (topic x & 직접 작성한 processor)

GET http://localhost:8080/pipeline/nontopic/start?count=1000000
Accept: application/json



### 파이프라인 실행 (topic x & 직접 작성한 processor & 1단계 2단계를 나누지 않고 한 번에 실행)

GET http://localhost:8080/pipeline/stepminifiednontopic/start?count=1000000
Accept: application/json



### 파이프라인 실행 (topic x & 직접 작성한 processor & 1단계 2단계를 나누지 않고 한 번에 실행 & 순서 보장 제약 추가)

GET http://localhost:8080/pipeline/orderingstepminifiednontopic/start?count=1000000
Accept: application/json



### 파이프라인 실행 (topic x & 직접 작성한 processor & 1단계 2단계를 나누지 않고 한 번에 실행 & 불필요한 sink#next 호출 제거)

GET http://localhost:8080/pipeline/efficientstepminifiednontopic/start?count=1000000
Accept: application/json



### 파이프라인 실행 (non fanout)

GET http://localhost:8080/pipeline/nonfanout/start?count=1000000
Accept: application/json



### 파이프라인 실행 (groupby)

GET http://localhost:8080/pipeline/groupby/start?count=1000000
Accept: application/json



### 파이프라인 실행 (groupby - advanced)

GET http://localhost:8080/pipeline/advanced/groupby/start?count=1000000
Accept: application/json

###


